### ISSUE TITLE
Not working after upgrade to PHP 7.3.0

### ISSUE THREAD

**Issue by dciancu** [laravel/tinker#63] opened 2018-12-08 12:39 UTC
* Laravel Version: 5.7.16
* PHP Version: 7.3.0

Please advise if this is a PsyShell bug, in which case I will file this issue at their repo.

After upgrading PHP to 7.3.0 - latest version (and Xdebug to 2.7.0beta1 latest version compatible with PHP 7.3, in case it matters), tinker is no longer working. It launches correctly but I after I input a command it just exits with no error, nothing written to log file and status code 0.

**Comment by dportalesr** [comment] 2018-12-08 13:37
I can confirm this.

**Comment by alphametric** [comment] 2018-12-10 09:38
Here's a workaround that appears to work until the issue is addressed:

https://github.com/bobthecow/psysh/issues/540#issuecomment-445546060

**Comment by driesvints** [comment] 2018-12-10 12:35
This indeed seems to be a PsyShell problem but I'm going to leave this open to follow up. Please wait until they solve it so we can release a patch with their fix.

**Comment by hulkur** [comment] 2018-12-11 08:41
In php.ini set `pcre.jit=0`

**Comment by belguinan** [comment] 2018-12-14 15:56
Same issue.

**Comment by dinhquochan** [comment] 2018-12-21 13:40
Same issue.

**Comment by driesvints** [comment] 2018-12-21 14:39
I'm going to lock this issue here because I doubt that anyone can contribute something useful here besides reporting that they also have the issue. If you have feedback on how to solve this please post on the issue from PsyShell.

**Comment by driesvints** [comment] 2019-03-11 15:29
I'm closing this issue as this isn't an issue with tinker itself. I've pinned the issue to the issue tracker for now so people who installed PHP with Homebrew can still find it easily.

**Closed** 2019-03-11 15:28 UTC
Labels: bug

**Comment by driesvints** [comment] 2019-10-30 19:28
FYI: as of PHP 7.3.11 this seems to be finally fixed: https://github.com/bobthecow/psysh/issues/540#issuecomment-547847844
